import SideBar from "@/components/custom/SideBar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"],weight:['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main
          className="grid grid-cols-[250px_minmax(100px,1fr)] grid-rows-[60px_minmax(100px,1fr)_50px] 
  bg-red-400 h-screen">
          <header className="p-2 bg-cyan-300 col-start-2 col-span-4 ">
            header
          </header>
          <aside className="flex flex-col justify-start items-center gap-5 p-2 bg-[#0F75B1] row-start-1 row-end-4"><SideBar/></aside>
          <section className="bg-gray-400 "> {children}</section>
          <footer className="p-2 bg-cyan-800  col-start-2 col-span-4">
            footer
          </footer>
        </main>
      </body>
    </html>
  );
}
